// Generated by gencpp from file ex1_serial/Message.msg
// DO NOT EDIT!


#ifndef EX1_SERIAL_MESSAGE_MESSAGE_H
#define EX1_SERIAL_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ex1_serial
{
template <class ContainerAllocator>
struct Message_
{
  typedef Message_<ContainerAllocator> Type;

  Message_()
    : data()
    , size(0)  {
    }
  Message_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , size(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;

   typedef uint8_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::ex1_serial::Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex1_serial::Message_<ContainerAllocator> const> ConstPtr;

}; // struct Message_

typedef ::ex1_serial::Message_<std::allocator<void> > Message;

typedef boost::shared_ptr< ::ex1_serial::Message > MessagePtr;
typedef boost::shared_ptr< ::ex1_serial::Message const> MessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex1_serial::Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex1_serial::Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ex1_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ex1_serial': ['/home/rovertx2/HERO_EX1/src/ex1_serial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ex1_serial::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex1_serial::Message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex1_serial::Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex1_serial::Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex1_serial::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex1_serial::Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex1_serial::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d65c7bbd4f88c12c49b0057e6c0ecce";
  }

  static const char* value(const ::ex1_serial::Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d65c7bbd4f88c12ULL;
  static const uint64_t static_value2 = 0xc49b0057e6c0ecceULL;
};

template<class ContainerAllocator>
struct DataType< ::ex1_serial::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex1_serial/Message";
  }

  static const char* value(const ::ex1_serial::Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex1_serial::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom data type for packets\n"
"uint8[] data\n"
"uint8 size\n"
;
  }

  static const char* value(const ::ex1_serial::Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex1_serial::Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex1_serial::Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex1_serial::Message_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "size: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX1_SERIAL_MESSAGE_MESSAGE_H
