// Generated by gencpp from file teleop/Command.msg
// DO NOT EDIT!


#ifndef TELEOP_MESSAGE_COMMAND_H
#define TELEOP_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teleop
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : id(0)
    , cmd(0)
    , len(0)
    , opt()  {
      opt.assign(0);
  }
  Command_(const ContainerAllocator& _alloc)
    : id(0)
    , cmd(0)
    , len(0)
    , opt()  {
  (void)_alloc;
      opt.assign(0);
  }



   typedef uint16_t _id_type;
  _id_type id;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef uint8_t _len_type;
  _len_type len;

   typedef boost::array<uint8_t, 16>  _opt_type;
  _opt_type opt;





  typedef boost::shared_ptr< ::teleop::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teleop::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::teleop::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::teleop::Command > CommandPtr;
typedef boost::shared_ptr< ::teleop::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teleop::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teleop::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'teleop': ['/home/rovertx2/HERO_EX1/src/teleop/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::teleop::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teleop::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "491437395421608172e700163ad99a96";
  }

  static const char* value(const ::teleop::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4914373954216081ULL;
  static const uint64_t static_value2 = 0x72e700163ad99a96ULL;
};

template<class ContainerAllocator>
struct DataType< ::teleop::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teleop/Command";
  }

  static const char* value(const ::teleop::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teleop::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom data type for command messages. \n"
"uint16 id\n"
"uint8 cmd\n"
"uint8 len \n"
"uint8[16] opt \n"
;
  }

  static const char* value(const ::teleop::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teleop::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cmd);
      stream.next(m.len);
      stream.next(m.opt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teleop::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teleop::Command_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    s << indent << "opt[]" << std::endl;
    for (size_t i = 0; i < v.opt.size(); ++i)
    {
      s << indent << "  opt[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.opt[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELEOP_MESSAGE_COMMAND_H
